### ISSUE TITLE
Update to use Active Federation ID and Multi mints

### ISSUE THREAD

**Issue by Kodylow** [Kodylow/fedimint-sdk-go#1]
This sdk needs to be updated to reflect the same structure as https://github.com/kodylow/fedimint-ts where it sets an active federation ID and passes the ID for federation specific endpoints in https://github.com/kodylow/fedimint-http (ln, mint, and onchain) 

fedimint-http and fedimint-ts are the reference impls, fedimint-go just need to be updated to mirror them

**Comment by PsychoPunkSage** [comment]
Hi @Kodylow 
I would like to attempt this issue

**Comment by PsychoPunkSage** [comment]
Hi @Kodylow I made a PR to do necessary changes.. Please review it.

**Comment by Kodylow** [comment]
requested changes

**Comment by Kodylow** [comment]
here's a python reference, just made the same updates to this one that need to made to fedimint-go. Fedimint-go needs to adjust its types too though to match the responses from fedimint-http

https://github.com/Kodylow/fedimint-py/commit/817ae2b3d9dc8d6dffe46fe2cfbca1c8f208b2ac

**Comment by Kodylow** [comment]
closed with PR
