### ISSUE TITLE
Add missing methods for new fedimint-http methods

### ISSUE THREAD

**Issue by Kodylow** [Kodylow/fedimint-sdk-go#4]
Create method feature parity with https://github.com/kodylow/fedimint-ts , added new endpoints to admin with new fedimint-http version

**Comment by PsychoPunkSage** [comment]
Hi @Kodylow,
I have yet again changed the FileSystem. and I think its much better and precise now. (Literally mirror of `fedimint-ts`)..
Here is the Tree..
```
.
├── assets
│   └── fedimint-gophers.png
├── cmd
│   └── main.go
├── flake.nix
├── go.mod
├── go.sum
├── pkg
│   └── fedimint
│       ├── client.go
│       └── types
│           ├── common.go
│           └── modules
│               ├── ln.go
│               ├── mint.go
│               └── wallet.go
└── README.md
```
I am thinking of creating a separate PR for this (filesystem change) and then tackle `Issue::> missing methods...` in separate PR. Can I do that??

**Comment by Kodylow** [comment]
yes please, separate smaller PRs are better

**Comment by PsychoPunkSage** [comment]
Hi @Kodylow 
I have created a PR for this issue...
I have added required functions which I found missing in `fedimint-go` + I also updated pre-existing function so that they can use `FederationId`

Please review it.
Thank You

**Comment by Kodylow** [comment]
Please just link to PR and have explanation in the PR not in the issue, thank you

**Comment by PsychoPunkSage** [comment]
Hi @Kodylow 
I am trying to write the test cases. As you said that I have to make a `test.sh` file to make some test... and use `curl` to make request...
I tried, but I'm not totally clear about how to proceed, especially the `curl` part... like what endpoints I have to use + what structure I have to use to make request...
Can provide me with some resources so that I can use those as a base to write test cases?
Thank You

**Comment by Kodylow** [comment]
Let's pair on this today in fedimint discord to get you started, shoot me a dm there

**Comment by PsychoPunkSage** [comment]
Hi @Kodylow 
I think you can close this issue as the corresponding PR is merged... If you want you can open a new issue for `Test Scripts` (which I'm currently working on)
